[ssdlite_mobiledet_cpu_320x320_coco_2020_05_19]
title=mobilenet_cpu
width=320
height=320
channels=3
score=50
iou=50
post=ssd

[ssd_mobilenet_v3_large_coco_2020_01_14]
title=mobile_v3_large
width=320
height=320
channels=3
score=50
iou=50
post=ssd

[ssd_mobilenet_v3_small_coco_2020_01_14]
title=mobile_v3_small
width=320
height=320
channels=3
score=50
iou=50
post=ssd

[lite-model_efficientdet_lite0_int8]
title=efficient_net
width=320
height=320
channels=3
score=50
iou=50
post=ssd

[yolov3-416-int8]
title=yolov3-416-int8
width=416
height=416
channels=3
score=50
iou=50
default=1
post=yolo

;[yolov3-tiny-416-int8]
;title=yolov3-tiny-416-int8
;width=416
;height=416
;channels=3
;score=50
;iou=50
;post=yolo
